### ISSUE TITLE
overlay-script for user creation fails on ubuntu:22.04 base

### ISSUE THREAD

**Issue by jnsgruk** [canonical/rockcraft#117] opened 2022-10-04 08:33 UTC
I've been experimenting (again!) and noticed that my [trick for creating a user](https://github.com/jnsgruk/traefik-rock/blob/74aca1b4651209374cad77bb76063adccba9d77d/rockcraft.yaml#L33-L42) in the resulting image doesn't work on 22.04. 

For an example, please see this [PR](https://github.com/jnsgruk/traefik-rock/pull/5) and resulting [CI failure](https://github.com/jnsgruk/traefik-rock/actions/runs/3180578163/jobs/5184322471#step:5:17).

I've done some troubleshooting, but can't understand why it's looking at `apt` at all in this case. Reproducible on another `rockcraft.yaml`, too.

Thanks! :)

**Comment by jnsgruk** [comment] 2022-10-04 09:19
Similar result here: https://github.com/jnsgruk/seldon-core-operator-rock/pull/2/checks#step:5:13

**Comment by sergiusens** [comment] 2022-10-04 18:44
OK, to make apt update less trigger happy we need to not update on any overlay entry but only on use of overlay packages -> https://github.com/canonical/craft-parts/blob/d5ed9639f9272797a3c1703cc1afdb94720bf37f/craft_parts/executor/executor.py#L94

**Comment by cmatsuoka** [comment] 2022-10-12 16:29
Problem seems to be caused by char dev permission issues when bind mounting. This problem also exists in 20.04 but didn't cause a fatal exit when updating the packages list, however this must be fixed in craft-parts so that other commands running in the overlay chroot could work properly.

**Comment by cmatsuoka** [comment] 2022-10-13 16:07
Fixed craft-parts to bind mount `/dev` using `MS_REC` so that character devices can be used, as implemented in https://github.com/canonical/craft-parts/pull/295. Once integrated into rockcraft, this will allow proper building of images based on 22.04, and also allow overlay scripts to use `/dev/null` or other device nodes inside the overlay chroot.
```
$ rockcraft 
Launching instance...                                                                                                                                                                          
Retrieved base ubuntu:22.04 for amd64                                                                                                                                                          
Extracted ubuntu:22.04                                                                                                                                                                         
Executed: pull default-config                                                                                                                                                                  
Executed: pull non-root-user                                                                                                                                                                   
Executed: pull pebble                                                                                                                                                                          
Executed: pull traefik                                                                                                                                                                         
Executed: overlay default-config                                                                                                                                                               
Executed: overlay non-root-user                                                                                                                                                                
Executed: overlay pebble                                                                                                                                                                       
Executed: overlay traefik                                                                                                                                                                      
Executed: build default-config                                                                                                                                                                 
Executed: skip pull default-config (already ran)                                                                                                                                               
Executed: skip overlay default-config (already ran)                                                                                                                                            
Executed: skip build default-config (already ran)                                                                                                                                              
Executed: stage default-config (required to build 'non-root-user')                                                                                                                             
Executed: build non-root-user                                                                                                                                                                  
Executed: build pebble                                                                                                                                                                         
Executed: build traefik                                                                                                                                                                        
Executed: skip stage default-config (already ran)                                                                                                                                              
Executed: stage non-root-user                                                                                                                                                                  
Executed: stage pebble                                                                                                                                                                         
Executed: stage traefik                                                                                                                                                                        
Executed: prime default-config                                                                                                                                                                 
Executed: prime non-root-user                                                                                                                                                                  
Executed: prime pebble                                                                                                                                                                         
Executed: prime traefik                                                                                                                                                                        
Executed parts lifecycle                                                                                                                                                                       
Created new layer                                                                                                                                                                              
Entrypoint set to ['/bin/pebble', 'run', '-v']                                                                                                                                                 
Cmd set to []                                                                                                                                                                                  
Labels and annotations set to ['org.opencontainers.image.version=2.9.1', 'org.opencontainers.image.title=traefik', 'org.opencontainers.image.ref.name=traefik', 'org.opencontainers.image.licenses=Apache-2.0', 'org.opencontainers.image.created=2022-10-13T16:05:32.395157+00:00', 'org.opencontainers.image.base.digest=35fb073f9e56eb84041b0745cb714eff0f7b225ea9e024f703cab56aaa5c7720']  
Exported to OCI archive 'traefik_2.9.1_amd64.rock'

```

**Closed** 2022-10-14 19:30 UTC
